from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogDiag1(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(560, 560))
        Dialog.setMaximumSize(QtCore.QSize(560, 560))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/thumbs/diagonal/diag_1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWhatsThis("")
        Dialog.setAccessibleDescription("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 560, 560))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(560, 560))
        self.label.setMaximumSize(QtCore.QSize(560, 560))
        self.label.setAutoFillBackground(True)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../pics/main/diagonal/diag_1.jpg"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_S = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_S.setGeometry(QtCore.QRect(153, 335, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_S.setFont(font)
        self.lineEdit_S.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_S.setAutoFillBackground(True)
        self.lineEdit_S.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_S.setText("")
        self.lineEdit_S.setMaxLength(3)
        self.lineEdit_S.setFrame(False)
        self.lineEdit_S.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.lineEdit_S.setObjectName("lineEdit")
        self.lineEdit_H = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_H.setGeometry(QtCore.QRect(40, 245, 41, 101))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_H.setFont(font)
        self.lineEdit_H.setTabletTracking(False)
        self.lineEdit_H.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_H.setAutoFillBackground(False)
        self.lineEdit_H.setText("")
        self.lineEdit_H.setMaxLength(3)
        self.lineEdit_H.setFrame(False)
        self.lineEdit_H.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lineEdit_H.setObjectName("lineEdit_2")
        self.lineEdit_B = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_B.setGeometry(QtCore.QRect(185, 432, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_B.setFont(font)
        self.lineEdit_B.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_B.setText("")
        self.lineEdit_B.setMaxLength(3)
        self.lineEdit_B.setFrame(False)
        self.lineEdit_B.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.lineEdit_B.setObjectName("lineEdit_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 9, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setFrame(False)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(210, 49, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setFrame(False)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_C = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_C.setGeometry(QtCore.QRect(443, 255, 41, 81))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_C.setFont(font)
        self.lineEdit_C.setTabletTracking(False)
        self.lineEdit_C.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_C.setAutoFillBackground(False)
        self.lineEdit_C.setText("")
        self.lineEdit_C.setMaxLength(3)
        self.lineEdit_C.setFrame(False)
        self.lineEdit_C.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lineEdit_C.setObjectName("lineEdit_3")

        self.screenshotButton = QtWidgets.QPushButton(Dialog)
        self.screenshotButton.setGeometry(QtCore.QRect(510, 15, 41, 41))
        self.screenshotButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/thumbs/screenshotbtn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.screenshotButton.setIcon(icon)
        self.screenshotButton.setIconSize(QtCore.QSize(35, 35))
        self.screenshotButton.setShortcut("")
        self.screenshotButton.setDefault(False)
        self.screenshotButton.setFlat(True)
        self.screenshotButton.setObjectName("screenshotButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Раскос"))
        self.label_2.setText(_translate("Dialog", "Производитель:"))
        self.label_3.setText(_translate("Dialog", "Тип (или рама):"))


class Ui_DialogDiag2(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(560, 560))
        Dialog.setMaximumSize(QtCore.QSize(560, 560))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/thumbs/diagonal/diag_1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWhatsThis("")
        Dialog.setAccessibleDescription("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 560, 560))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(560, 560))
        self.label.setMaximumSize(QtCore.QSize(560, 560))
        self.label.setAutoFillBackground(True)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../pics/main/diagonal/diag_2.jpg"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_S = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_S.setGeometry(QtCore.QRect(405, 326, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_S.setFont(font)
        self.lineEdit_S.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_S.setAutoFillBackground(True)
        self.lineEdit_S.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_S.setText("")
        self.lineEdit_S.setMaxLength(3)
        self.lineEdit_S.setFrame(False)
        self.lineEdit_S.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.lineEdit_S.setObjectName("lineEdit")
        self.lineEdit_H = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_H.setGeometry(QtCore.QRect(60, 245, 41, 101))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_H.setFont(font)
        self.lineEdit_H.setTabletTracking(False)
        self.lineEdit_H.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_H.setAutoFillBackground(False)
        self.lineEdit_H.setText("")
        self.lineEdit_H.setMaxLength(3)
        self.lineEdit_H.setFrame(False)
        self.lineEdit_H.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lineEdit_H.setObjectName("lineEdit_2")
        self.lineEdit_C = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_C.setGeometry(QtCore.QRect(221, 420, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_C.setFont(font)
        self.lineEdit_C.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_C.setText("")
        self.lineEdit_C.setMaxLength(3)
        self.lineEdit_C.setFrame(False)
        self.lineEdit_C.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.lineEdit_C.setObjectName("lineEdit_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 9, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setFrame(False)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(210, 49, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setFrame(False)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_B = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_B.setGeometry(QtCore.QRect(221, 115, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_B.setFont(font)
        self.lineEdit_B.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_B.setText("")
        self.lineEdit_B.setMaxLength(3)
        self.lineEdit_B.setFrame(False)
        self.lineEdit_B.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.lineEdit_B.setObjectName("lineEdit_5")

        self.screenshotButton = QtWidgets.QPushButton(Dialog)
        self.screenshotButton.setGeometry(QtCore.QRect(510, 15, 41, 41))
        self.screenshotButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/thumbs/screenshotbtn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.screenshotButton.setIcon(icon)
        self.screenshotButton.setIconSize(QtCore.QSize(35, 35))
        self.screenshotButton.setShortcut("")
        self.screenshotButton.setDefault(False)
        self.screenshotButton.setFlat(True)
        self.screenshotButton.setObjectName("screenshotButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Раскос"))
        self.label_2.setText(_translate("Dialog", "Производитель:"))
        self.label_3.setText(_translate("Dialog", "Тип (или рама):"))


class Ui_DialogDiag3(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(560, 560))
        Dialog.setMaximumSize(QtCore.QSize(560, 560))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/thumbs/diagonal/diag_1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWhatsThis("")
        Dialog.setAccessibleDescription("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 560, 560))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(560, 560))
        self.label.setMaximumSize(QtCore.QSize(560, 560))
        self.label.setAutoFillBackground(True)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../pics/main/diagonal/diag_3.jpg"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_S = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_S.setGeometry(QtCore.QRect(245, 335, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_S.setFont(font)
        self.lineEdit_S.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_S.setAutoFillBackground(True)
        self.lineEdit_S.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_S.setText("")
        self.lineEdit_S.setMaxLength(3)
        self.lineEdit_S.setFrame(False)
        self.lineEdit_S.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.lineEdit_S.setObjectName("lineEdit")
        self.lineEdit_H = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_H.setGeometry(QtCore.QRect(116, 245, 41, 101))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_H.setFont(font)
        self.lineEdit_H.setTabletTracking(False)
        self.lineEdit_H.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_H.setAutoFillBackground(False)
        self.lineEdit_H.setText("")
        self.lineEdit_H.setMaxLength(3)
        self.lineEdit_H.setFrame(False)
        self.lineEdit_H.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lineEdit_H.setObjectName("lineEdit_2")
        self.lineEdit_B = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_B.setGeometry(QtCore.QRect(237, 422, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_B.setFont(font)
        self.lineEdit_B.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_B.setText("")
        self.lineEdit_B.setMaxLength(3)
        self.lineEdit_B.setFrame(False)
        self.lineEdit_B.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.lineEdit_B.setObjectName("lineEdit_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 9, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setFrame(False)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(210, 49, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setFrame(False)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.screenshotButton = QtWidgets.QPushButton(Dialog)
        self.screenshotButton.setGeometry(QtCore.QRect(510, 15, 41, 41))
        self.screenshotButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/thumbs/screenshotbtn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.screenshotButton.setIcon(icon)
        self.screenshotButton.setIconSize(QtCore.QSize(35, 35))
        self.screenshotButton.setShortcut("")
        self.screenshotButton.setDefault(False)
        self.screenshotButton.setFlat(True)
        self.screenshotButton.setObjectName("screenshotButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Раскос"))
        self.label_2.setText(_translate("Dialog", "Производитель:"))
        self.label_3.setText(_translate("Dialog", "Тип (или рама):"))


class Ui_DialogDiag4(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(560, 560))
        Dialog.setMaximumSize(QtCore.QSize(560, 560))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/thumbs/diagonal/diag_1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWhatsThis("")
        Dialog.setAccessibleDescription("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 560, 560))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(560, 560))
        self.label.setMaximumSize(QtCore.QSize(560, 560))
        self.label.setAutoFillBackground(True)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../pics/main/diagonal/diag_4.jpg"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_S = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_S.setGeometry(QtCore.QRect(90, 302, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_S.setFont(font)
        self.lineEdit_S.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_S.setAutoFillBackground(True)
        self.lineEdit_S.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_S.setText("")
        self.lineEdit_S.setMaxLength(3)
        self.lineEdit_S.setFrame(False)
        self.lineEdit_S.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.lineEdit_S.setObjectName("lineEdit")
        self.lineEdit_H = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_H.setGeometry(QtCore.QRect(445, 255, 41, 81))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_H.setFont(font)
        self.lineEdit_H.setTabletTracking(False)
        self.lineEdit_H.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_H.setAutoFillBackground(False)
        self.lineEdit_H.setText("")
        self.lineEdit_H.setMaxLength(3)
        self.lineEdit_H.setFrame(False)
        self.lineEdit_H.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lineEdit_H.setObjectName("lineEdit_2")
        self.lineEdit_B = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_B.setGeometry(QtCore.QRect(195, 183, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_B.setFont(font)
        self.lineEdit_B.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_B.setText("")
        self.lineEdit_B.setMaxLength(3)
        self.lineEdit_B.setFrame(False)
        self.lineEdit_B.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.lineEdit_B.setObjectName("lineEdit_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 9, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setFrame(False)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(210, 49, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setFrame(False)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.screenshotButton = QtWidgets.QPushButton(Dialog)
        self.screenshotButton.setGeometry(QtCore.QRect(510, 15, 41, 41))
        self.screenshotButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/thumbs/screenshotbtn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.screenshotButton.setIcon(icon)
        self.screenshotButton.setIconSize(QtCore.QSize(35, 35))
        self.screenshotButton.setShortcut("")
        self.screenshotButton.setDefault(False)
        self.screenshotButton.setFlat(True)
        self.screenshotButton.setObjectName("screenshotButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Раскос"))
        self.label_2.setText(_translate("Dialog", "Производитель:"))
        self.label_3.setText(_translate("Dialog", "Тип (или рама):"))


class Ui_DialogDiag5(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(560, 560))
        Dialog.setMaximumSize(QtCore.QSize(560, 560))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/thumbs/diagonal/diag_1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWhatsThis("")
        Dialog.setAccessibleDescription("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 560, 560))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(560, 560))
        self.label.setMaximumSize(QtCore.QSize(560, 560))
        self.label.setAutoFillBackground(True)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../pics/main/diagonal/diag_5.jpg"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_S = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_S.setGeometry(QtCore.QRect(200, 305, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_S.setFont(font)
        self.lineEdit_S.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_S.setAutoFillBackground(True)
        self.lineEdit_S.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_S.setText("")
        self.lineEdit_S.setMaxLength(3)
        self.lineEdit_S.setFrame(False)
        self.lineEdit_S.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.lineEdit_S.setObjectName("lineEdit")
        self.lineEdit_H = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_H.setGeometry(QtCore.QRect(70, 190, 41, 171))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_H.setFont(font)
        self.lineEdit_H.setTabletTracking(False)
        self.lineEdit_H.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_H.setAutoFillBackground(False)
        self.lineEdit_H.setText("")
        self.lineEdit_H.setMaxLength(3)
        self.lineEdit_H.setFrame(False)
        self.lineEdit_H.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lineEdit_H.setObjectName("lineEdit_2")
        self.lineEdit_B = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_B.setGeometry(QtCore.QRect(210, 423, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_B.setFont(font)
        self.lineEdit_B.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_B.setText("")
        self.lineEdit_B.setMaxLength(3)
        self.lineEdit_B.setFrame(False)
        self.lineEdit_B.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.lineEdit_B.setObjectName("lineEdit_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 9, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setFrame(False)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(210, 49, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setFrame(False)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.screenshotButton = QtWidgets.QPushButton(Dialog)
        self.screenshotButton.setGeometry(QtCore.QRect(510, 15, 41, 41))
        self.screenshotButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/thumbs/screenshotbtn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.screenshotButton.setIcon(icon)
        self.screenshotButton.setIconSize(QtCore.QSize(35, 35))
        self.screenshotButton.setShortcut("")
        self.screenshotButton.setDefault(False)
        self.screenshotButton.setFlat(True)
        self.screenshotButton.setObjectName("screenshotButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Раскос"))
        self.label_2.setText(_translate("Dialog", "Производитель:"))
        self.label_3.setText(_translate("Dialog", "Тип (или рама):"))


class Ui_DialogDiag6(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(560, 560))
        Dialog.setMaximumSize(QtCore.QSize(560, 560))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/thumbs/diagonal/diag_1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWhatsThis("")
        Dialog.setAccessibleDescription("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 560, 560))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(560, 560))
        self.label.setMaximumSize(QtCore.QSize(560, 560))
        self.label.setAutoFillBackground(True)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../pics/main/diagonal/diag_6.jpg"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_S = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_S.setGeometry(QtCore.QRect(87, 316, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_S.setFont(font)
        self.lineEdit_S.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_S.setAutoFillBackground(True)
        self.lineEdit_S.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_S.setText("")
        self.lineEdit_S.setMaxLength(3)
        self.lineEdit_S.setFrame(False)
        self.lineEdit_S.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing)
        self.lineEdit_S.setObjectName("lineEdit")
        self.lineEdit_H = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_H.setGeometry(QtCore.QRect(450, 190, 41, 171))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_H.setFont(font)
        self.lineEdit_H.setTabletTracking(False)
        self.lineEdit_H.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_H.setAutoFillBackground(False)
        self.lineEdit_H.setText("")
        self.lineEdit_H.setMaxLength(3)
        self.lineEdit_H.setFrame(False)
        self.lineEdit_H.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lineEdit_H.setObjectName("lineEdit_2")
        self.lineEdit_B = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_B.setGeometry(QtCore.QRect(180, 423, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_B.setFont(font)
        self.lineEdit_B.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_B.setText("")
        self.lineEdit_B.setMaxLength(3)
        self.lineEdit_B.setFrame(False)
        self.lineEdit_B.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.lineEdit_B.setObjectName("lineEdit_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 9, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setFrame(False)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(210, 49, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setFrame(False)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.screenshotButton = QtWidgets.QPushButton(Dialog)
        self.screenshotButton.setGeometry(QtCore.QRect(510, 15, 41, 41))
        self.screenshotButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/thumbs/screenshotbtn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.screenshotButton.setIcon(icon)
        self.screenshotButton.setIconSize(QtCore.QSize(35, 35))
        self.screenshotButton.setShortcut("")
        self.screenshotButton.setDefault(False)
        self.screenshotButton.setFlat(True)
        self.screenshotButton.setObjectName("screenshotButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Раскос"))
        self.label_2.setText(_translate("Dialog", "Производитель:"))
        self.label_3.setText(_translate("Dialog", "Тип (или рама):"))


class Ui_DialogDiag7(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(560, 560))
        Dialog.setMaximumSize(QtCore.QSize(560, 560))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/thumbs/diagonal/diag_1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWhatsThis("")
        Dialog.setAccessibleDescription("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 560, 560))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(560, 560))
        self.label.setMaximumSize(QtCore.QSize(560, 560))
        self.label.setAutoFillBackground(True)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../pics/main/diagonal/diag_7.jpg"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_S = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_S.setGeometry(QtCore.QRect(114, 333, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_S.setFont(font)
        self.lineEdit_S.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_S.setAutoFillBackground(True)
        self.lineEdit_S.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_S.setText("")
        self.lineEdit_S.setMaxLength(3)
        self.lineEdit_S.setFrame(False)
        self.lineEdit_S.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing)
        self.lineEdit_S.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 9, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setFrame(False)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(210, 49, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setFrame(False)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_H = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_H.setGeometry(QtCore.QRect(418, 393, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_H.setFont(font)
        self.lineEdit_H.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_H.setMaxLength(4)
        self.lineEdit_H.setFrame(False)
        self.lineEdit_H.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.lineEdit_H.setObjectName("lineEdit_H")

        self.screenshotButton = QtWidgets.QPushButton(Dialog)
        self.screenshotButton.setGeometry(QtCore.QRect(510, 15, 41, 41))
        self.screenshotButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/thumbs/screenshotbtn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.screenshotButton.setIcon(icon)
        self.screenshotButton.setIconSize(QtCore.QSize(35, 35))
        self.screenshotButton.setShortcut("")
        self.screenshotButton.setDefault(False)
        self.screenshotButton.setFlat(True)
        self.screenshotButton.setObjectName("screenshotButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Раскос"))
        self.label_2.setText(_translate("Dialog", "Производитель:"))
        self.label_3.setText(_translate("Dialog", "Тип (или рама):"))
        self.lineEdit_H.setText(_translate("Dialog", "Ø"))
