# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'framedimui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowFrame(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        MainWindow.setMinimumSize(QtCore.QSize(250, 700))
        MainWindow.setMaximumSize(QtCore.QSize(800, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/thumbs/framemodul.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_d0 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_d0.setGeometry(QtCore.QRect(160, 630, 50, 20))
        self.lineEdit_d0.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_d0.setMaxLength(4)
        self.lineEdit_d0.setFrame(False)
        self.lineEdit_d0.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lineEdit_d0.setObjectName("lineEdit_d0")
        self.bgrnd = QtWidgets.QLabel(self.centralwidget)
        self.bgrnd.setGeometry(QtCore.QRect(0, 0, 250, 671))
        self.bgrnd.setText("")
        self.bgrnd.setPixmap(QtGui.QPixmap("../pics/frame/Bgrnd.png"))
        self.bgrnd.setScaledContents(True)
        self.bgrnd.setObjectName("bgrnd")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(229, -10, 41, 701))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(260, 10, 531, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 60, 102, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_variant = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_variant.setGeometry(QtCore.QRect(370, 60, 41, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_variant.setFont(font)
        self.lineEdit_variant.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_variant.setMaxLength(2)
        self.lineEdit_variant.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_variant.setObjectName("lineEdit_variant")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(260, 230, 531, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(430, 60, 102, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_frame = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_frame.setGeometry(QtCore.QRect(530, 60, 261, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_frame.setFont(font)
        self.lineEdit_frame.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_frame.setMaxLength(10)
        self.lineEdit_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_frame.setObjectName("lineEdit_frame")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(260, 110, 131, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(400, 110, 391, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.pushButton_pp1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pp1.setGeometry(QtCore.QRect(540, 630, 241, 41))
        self.pushButton_pp1.setAutoFillBackground(False)
        self.pushButton_pp1.setDefault(True)
        self.pushButton_pp1.setFlat(False)
        self.pushButton_pp1.setObjectName("pushButton_pp1")
        self.label_g1 = QtWidgets.QLabel(self.centralwidget)
        self.label_g1.setGeometry(QtCore.QRect(0, 600, 230, 71))
        self.label_g1.setText("")
        self.label_g1.setPixmap(QtGui.QPixmap("../pics/frame/G1.png"))
        self.label_g1.setScaledContents(True)
        self.label_g1.setObjectName("label_g1")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(430, 250, 191, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(270, 290, 511, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_dg2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dg2.sizePolicy().hasHeightForWidth())
        self.pushButton_dg2.setSizePolicy(sizePolicy)
        self.pushButton_dg2.setMinimumSize(QtCore.QSize(120, 120))
        self.pushButton_dg2.setMaximumSize(QtCore.QSize(120, 120))
        self.pushButton_dg2.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_dg2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/thumbs/frdg2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_dg2.setIcon(icon)
        self.pushButton_dg2.setIconSize(QtCore.QSize(110, 110))
        self.pushButton_dg2.setFlat(False)
        self.pushButton_dg2.setObjectName("pushButton_dg2")
        self.gridLayout.addWidget(self.pushButton_dg2, 0, 3, 1, 1)
        self.pushButton_d1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_d1.sizePolicy().hasHeightForWidth())
        self.pushButton_d1.setSizePolicy(sizePolicy)
        self.pushButton_d1.setMinimumSize(QtCore.QSize(120, 120))
        self.pushButton_d1.setMaximumSize(QtCore.QSize(120, 120))
        self.pushButton_d1.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_d1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../pics/thumbs/frd1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_d1.setIcon(icon1)
        self.pushButton_d1.setIconSize(QtCore.QSize(110, 110))
        self.pushButton_d1.setFlat(False)
        self.pushButton_d1.setObjectName("pushButton_d1")
        self.gridLayout.addWidget(self.pushButton_d1, 0, 1, 1, 1)
        self.pushButton_dg1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dg1.sizePolicy().hasHeightForWidth())
        self.pushButton_dg1.setSizePolicy(sizePolicy)
        self.pushButton_dg1.setMinimumSize(QtCore.QSize(120, 120))
        self.pushButton_dg1.setMaximumSize(QtCore.QSize(120, 120))
        self.pushButton_dg1.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_dg1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../pics/thumbs/frdg1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_dg1.setIcon(icon2)
        self.pushButton_dg1.setIconSize(QtCore.QSize(110, 110))
        self.pushButton_dg1.setFlat(False)
        self.pushButton_dg1.setObjectName("pushButton_dg1")
        self.gridLayout.addWidget(self.pushButton_dg1, 0, 0, 1, 1)
        self.pushButton_g2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_g2.sizePolicy().hasHeightForWidth())
        self.pushButton_g2.setSizePolicy(sizePolicy)
        self.pushButton_g2.setMinimumSize(QtCore.QSize(120, 120))
        self.pushButton_g2.setMaximumSize(QtCore.QSize(120, 120))
        self.pushButton_g2.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_g2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../pics/thumbs/frg2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_g2.setIcon(icon3)
        self.pushButton_g2.setIconSize(QtCore.QSize(110, 110))
        self.pushButton_g2.setFlat(False)
        self.pushButton_g2.setObjectName("pushButton_g2")
        self.gridLayout.addWidget(self.pushButton_g2, 1, 0, 1, 1)
        self.pushButton_d2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_d2.sizePolicy().hasHeightForWidth())
        self.pushButton_d2.setSizePolicy(sizePolicy)
        self.pushButton_d2.setMinimumSize(QtCore.QSize(120, 120))
        self.pushButton_d2.setMaximumSize(QtCore.QSize(120, 120))
        self.pushButton_d2.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_d2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../pics/thumbs/frd2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_d2.setIcon(icon4)
        self.pushButton_d2.setIconSize(QtCore.QSize(110, 110))
        self.pushButton_d2.setFlat(False)
        self.pushButton_d2.setObjectName("pushButton_d2")
        self.gridLayout.addWidget(self.pushButton_d2, 0, 2, 1, 1)
        self.pushButton_nd = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_nd.sizePolicy().hasHeightForWidth())
        self.pushButton_nd.setSizePolicy(sizePolicy)
        self.pushButton_nd.setMinimumSize(QtCore.QSize(120, 120))
        self.pushButton_nd.setMaximumSize(QtCore.QSize(120, 120))
        self.pushButton_nd.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_nd.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../pics/thumbs/frg1x.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_nd.setIcon(icon5)
        self.pushButton_nd.setIconSize(QtCore.QSize(110, 110))
        self.pushButton_nd.setFlat(False)
        self.pushButton_nd.setObjectName("pushButton_nd")
        self.gridLayout.addWidget(self.pushButton_nd, 1, 2, 1, 1)
        self.pushButton_canc = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_canc.sizePolicy().hasHeightForWidth())
        self.pushButton_canc.setSizePolicy(sizePolicy)
        self.pushButton_canc.setMinimumSize(QtCore.QSize(120, 120))
        self.pushButton_canc.setMaximumSize(QtCore.QSize(120, 120))
        self.pushButton_canc.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_canc.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../pics/thumbs/retarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_canc.setIcon(icon6)
        self.pushButton_canc.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_canc.setFlat(True)
        self.pushButton_canc.setObjectName("../pushButton_canc")
        self.gridLayout.addWidget(self.pushButton_canc, 1, 3, 1, 1)
        self.label_ng = QtWidgets.QLabel(self.centralwidget)
        self.label_ng.setGeometry(QtCore.QRect(0, 600, 230, 71))
        self.label_ng.setText("")
        self.label_ng.setPixmap(QtGui.QPixmap("../pics/frame/NG.png"))
        self.label_ng.setScaledContents(True)
        self.label_ng.setObjectName("label_ng")
        self.pushButton_clr = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clr.setGeometry(QtCore.QRect(270, 570, 241, 41))
        self.pushButton_clr.setObjectName("pushButton_clr")
        self.pushButton_prnt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_prnt.setGeometry(QtCore.QRect(270, 630, 241, 41))
        self.pushButton_prnt.setObjectName("pushButton_prnt")
        self.pushButton_eqcheck = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_eqcheck.setGeometry(QtCore.QRect(550, 560, 40, 40))
        self.pushButton_eqcheck.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_eqcheck.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_eqcheck.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../pics/thumbs/checkbox/N.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_eqcheck.setIcon(icon7)
        self.pushButton_eqcheck.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_eqcheck.setCheckable(False)
        self.pushButton_eqcheck.setChecked(False)
        self.pushButton_eqcheck.setFlat(True)
        self.pushButton_eqcheck.setObjectName("pushButton_eqcheck")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(600, 550, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(640, 570, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")

        self.pushButton_sum = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_canc.sizePolicy().hasHeightForWidth())
        self.pushButton_sum.setSizePolicy(sizePolicy)
        self.pushButton_sum.setMinimumSize(QtCore.QSize(120, 120))
        self.pushButton_sum.setMaximumSize(QtCore.QSize(120, 120))
        self.pushButton_sum.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_sum.setFont(font)
        self.pushButton_sum.setText("Проверить сумму\nразмеров")
        self.pushButton_sum.setFlat(True)
        self.pushButton_sum.setObjectName("../pushButton_sum")
        self.gridLayout.addWidget(self.pushButton_sum, 1, 1, 1, 1)

        self.label_dg1 = ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
        self.label_dg2 = ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
        self.label_d1 = ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
        self.label_d2 = ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
        self.label_g2 = ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
        self.lineEdit_d1 = ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

        for i in range (0,30):
            self.label_dg1[i] = QtWidgets.QLabel(self.centralwidget)
            self.label_dg1[i].setGeometry(QtCore.QRect(0, 562, 178, 72))
            self.label_dg1[i].setText("")
            self.label_dg1[i].setPixmap(QtGui.QPixmap("../pics/frame/DG1.png"))
            self.label_dg1[i].setScaledContents(True)
            self.label_dg1[i].setObjectName("label_dg1{}".format(i))
            self.label_dg1[i].hide()

            self.label_d1[i] = QtWidgets.QLabel(self.centralwidget)
            self.label_d1[i].setGeometry(QtCore.QRect(0, 512, 178, 72))
            self.label_d1[i].setText("")
            self.label_d1[i].setPixmap(QtGui.QPixmap("../pics/frame/D1.png"))
            self.label_d1[i].setScaledContents(True)
            self.label_d1[i].setObjectName("label_d1{}".format(i))
            self.label_d1[i].hide()

            self.label_d2[i] = QtWidgets.QLabel(self.centralwidget)
            self.label_d2[i].setGeometry(QtCore.QRect(0, 462, 178, 72))
            self.label_d2[i].setText("")
            self.label_d2[i].setPixmap(QtGui.QPixmap("../pics/frame/D2.png"))
            self.label_d2[i].setScaledContents(True)
            self.label_d2[i].setObjectName("label_d2{}".format(i))
            self.label_d2[i].hide()

            self.label_dg2[i] = QtWidgets.QLabel(self.centralwidget)
            self.label_dg2[i].setGeometry(QtCore.QRect(0, 362, 178, 72))
            self.label_dg2[i].setText("")
            self.label_dg2[i].setPixmap(QtGui.QPixmap("../pics/frame/DG2.png"))
            self.label_dg2[i].setScaledContents(True)
            self.label_dg2[i].setObjectName("label_dg2{}".format(i))
            self.label_dg2[i].hide()

            self.label_g2[i] = QtWidgets.QLabel(self.centralwidget)
            self.label_g2[i].setGeometry(QtCore.QRect(0, 314, 178, 72))
            self.label_g2[i].setText("")
            self.label_g2[i].setPixmap(QtGui.QPixmap("../pics/frame/G2.png"))
            self.label_g2[i].setScaledContents(True)
            self.label_g2[i].setObjectName("label_g2{}".format(i))
            self.label_g2[i].hide()

        for i in range(0, 60):
            self.lineEdit_d1[i] = QtWidgets.QLineEdit(self.centralwidget)
            self.lineEdit_d1[i].setGeometry(QtCore.QRect(145, 592, 50, 20))
            self.lineEdit_d1[i].setFocusPolicy(QtCore.Qt.ClickFocus)
            self.lineEdit_d1[i].setMaxLength(4)
            self.lineEdit_d1[i].setFrame(False)
            self.lineEdit_d1[i].setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
            self.lineEdit_d1[i].setObjectName("lineEdit_d1{}".format(i))
            self.lineEdit_d1[i].hide()

        self.bgrnd.raise_()
        self.label_ng.raise_()
        self.label_g1.raise_()
        self.lineEdit_d0.raise_()
        self.line.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label_4.raise_()
        self.lineEdit_variant.raise_()
        self.line_2.raise_()
        self.label_8.raise_()
        self.lineEdit_frame.raise_()
        self.label_9.raise_()
        self.textEdit.raise_()
        self.pushButton_pp1.raise_()
        self.label_10.raise_()
        self.gridLayoutWidget.raise_()
        self.pushButton_clr.raise_()
        self.pushButton_prnt.raise_()
        self.pushButton_eqcheck.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton_sum.raise_()

        for i in range(0,30):

            self.label_dg1[i].raise_()
            self.label_d1[i].raise_()
            self.label_d2[i].raise_()
            self.label_dg2[i].raise_()
            self.label_g2[i].raise_()

        for i in range(0, 60):
            self.lineEdit_d1[i].raise_()

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Отрисовка рам"))
        self.label_3.setText(_translate("MainWindow", "Производитель:"))
        self.label_4.setText(_translate("MainWindow", "Вариант №:"))
        self.label_8.setText(_translate("MainWindow", "Рама HxB:"))
        self.label_9.setText(_translate("MainWindow", "Комментарий:"))
        self.pushButton_pp1.setText(_translate("MainWindow", "Назад к подпятникам"))
        self.label_10.setText(_translate("MainWindow", "Добавить элементы:"))
        self.pushButton_clr.setText(_translate("MainWindow", "Очистить область построения"))
        self.pushButton_prnt.setText(_translate("MainWindow", "Вывести окно для скриншота"))
        self.label.setText(_translate("MainWindow", " Все следующие  размеры"))
        self.label_2.setText(_translate("MainWindow", "равны первому"))
