# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WMain.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 650))
        MainWindow.setMaximumSize(QtCore.QSize(800, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pics/icon/Podpyatnik.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 780, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 726, 434))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_F2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_F2.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_F2.setMaximumSize(QtCore.QSize(140, 140))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../pics/thumbs/F-2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_F2.setIcon(icon1)
        self.pushButton_F2.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_F2.setFlat(False)
        self.pushButton_F2.setObjectName("pushButton_F2")
        self.gridLayout.addWidget(self.pushButton_F2, 1, 1, 1, 1)
        self.pushButton_F4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_F4.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_F4.setMaximumSize(QtCore.QSize(140, 140))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../pics/thumbs/F-4.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_F4.setIcon(icon2)
        self.pushButton_F4.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_F4.setFlat(False)
        self.pushButton_F4.setObjectName("pushButton_F4")
        self.gridLayout.addWidget(self.pushButton_F4, 1, 3, 1, 1)
        self.pushButton_1_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_1_2.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_1_2.setMaximumSize(QtCore.QSize(140, 140))
        self.pushButton_1_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../pics/thumbs/1-2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_1_2.setIcon(icon3)
        self.pushButton_1_2.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_1_2.setFlat(False)
        self.pushButton_1_2.setObjectName("pushButton_1_2")
        self.gridLayout.addWidget(self.pushButton_1_2, 0, 1, 1, 1)
        self.pushButton_2_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2_2.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_2_2.setMaximumSize(QtCore.QSize(140, 140))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../pics/thumbs/2-2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2_2.setIcon(icon4)
        self.pushButton_2_2.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_2_2.setFlat(False)
        self.pushButton_2_2.setObjectName("pushButton_2_2")
        self.gridLayout.addWidget(self.pushButton_2_2, 0, 4, 1, 1)
        self.pushButton_F3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_F3.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_F3.setMaximumSize(QtCore.QSize(140, 140))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../pics/thumbs/F-3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_F3.setIcon(icon5)
        self.pushButton_F3.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_F3.setFlat(False)
        self.pushButton_F3.setObjectName("pushButton_F3")
        self.gridLayout.addWidget(self.pushButton_F3, 1, 2, 1, 1)
        self.pushButton_R1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_R1.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_R1.setMaximumSize(QtCore.QSize(140, 140))
        self.pushButton_R1.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../pics/thumbs/R-1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_R1.setIcon(icon6)
        self.pushButton_R1.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_R1.setFlat(False)
        self.pushButton_R1.setObjectName("pushButton_R1")
        self.gridLayout.addWidget(self.pushButton_R1, 0, 2, 1, 1)
        self.pushButton_1_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1_1.setSizePolicy(sizePolicy)
        self.pushButton_1_1.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_1_1.setMaximumSize(QtCore.QSize(140, 140))
        self.pushButton_1_1.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_1_1.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../pics/thumbs/1-1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_1_1.setIcon(icon7)
        self.pushButton_1_1.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_1_1.setFlat(False)
        self.pushButton_1_1.setObjectName("pushButton_1_1")
        self.gridLayout.addWidget(self.pushButton_1_1, 0, 0, 1, 1)
        self.pushButton_2_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2_1.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_2_1.setMaximumSize(QtCore.QSize(140, 140))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../pics/thumbs/2-1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2_1.setIcon(icon8)
        self.pushButton_2_1.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_2_1.setFlat(False)
        self.pushButton_2_1.setObjectName("pushButton_2_1")
        self.gridLayout.addWidget(self.pushButton_2_1, 0, 3, 1, 1)
        self.pushButton_F1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_F1.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_F1.setMaximumSize(QtCore.QSize(140, 140))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../pics/thumbs/F-1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_F1.setIcon(icon9)
        self.pushButton_F1.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_F1.setFlat(False)
        self.pushButton_F1.setObjectName("pushButton_F1")
        self.gridLayout.addWidget(self.pushButton_F1, 1, 0, 1, 1)
        self.pushButton_F8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_F8.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_F8.setMaximumSize(QtCore.QSize(140, 140))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../pics/thumbs/F-8.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_F8.setIcon(icon10)
        self.pushButton_F8.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_F8.setFlat(False)
        self.pushButton_F8.setObjectName("pushButton_F8")
        self.gridLayout.addWidget(self.pushButton_F8, 1, 4, 1, 1)
        self.pushButton_R4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_R4.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_R4.setMaximumSize(QtCore.QSize(140, 140))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../pics/thumbs/R-4.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_R4.setIcon(icon11)
        self.pushButton_R4.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_R4.setFlat(False)
        self.pushButton_R4.setObjectName("pushButton_R4")
        self.gridLayout.addWidget(self.pushButton_R4, 2, 1, 1, 1)
        self.pushButton_F9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_F9.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_F9.setMaximumSize(QtCore.QSize(140, 140))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../pics/thumbs/F-9.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_F9.setIcon(icon12)
        self.pushButton_F9.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_F9.setFlat(False)
        self.pushButton_F9.setObjectName("pushButton_F9")
        self.gridLayout.addWidget(self.pushButton_F9, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 726, 434))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_3_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3_2.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_3_2.setMaximumSize(QtCore.QSize(140, 140))
        self.pushButton_3_2.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../pics/thumbs/3-2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3_2.setIcon(icon13)
        self.pushButton_3_2.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_3_2.setFlat(False)
        self.pushButton_3_2.setObjectName("pushButton_3_2")
        self.gridLayout_2.addWidget(self.pushButton_3_2, 0, 1, 1, 1)
        self.pushButton_3_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3_3.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_3_3.setMaximumSize(QtCore.QSize(140, 140))
        self.pushButton_3_3.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../pics/thumbs/3-3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3_3.setIcon(icon14)
        self.pushButton_3_3.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_3_3.setFlat(False)
        self.pushButton_3_3.setObjectName("pushButton_3_3")
        self.gridLayout_2.addWidget(self.pushButton_3_3, 0, 2, 1, 1)
        self.pushButton_3_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3_4.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_3_4.setMaximumSize(QtCore.QSize(140, 140))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../pics/thumbs/3-4.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3_4.setIcon(icon15)
        self.pushButton_3_4.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_3_4.setFlat(False)
        self.pushButton_3_4.setObjectName("pushButton_3_4")
        self.gridLayout_2.addWidget(self.pushButton_3_4, 0, 3, 1, 1)
        self.pushButton_3_1 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3_1.sizePolicy().hasHeightForWidth())
        self.pushButton_3_1.setSizePolicy(sizePolicy)
        self.pushButton_3_1.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_3_1.setMaximumSize(QtCore.QSize(140, 140))
        self.pushButton_3_1.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_3_1.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("../pics/thumbs/3-1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3_1.setIcon(icon16)
        self.pushButton_3_1.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_3_1.setFlat(False)
        self.pushButton_3_1.setObjectName("pushButton_3_1")
        self.gridLayout_2.addWidget(self.pushButton_3_1, 0, 0, 1, 1)
        self.pushButton_F5 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_F5.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_F5.setMaximumSize(QtCore.QSize(140, 140))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("../pics/thumbs/F-5.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_F5.setIcon(icon17)
        self.pushButton_F5.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_F5.setFlat(False)
        self.pushButton_F5.setObjectName("pushButton_F5")
        self.gridLayout_2.addWidget(self.pushButton_F5, 0, 4, 1, 1)
        self.pushButton_F7 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_F7.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_F7.setMaximumSize(QtCore.QSize(140, 140))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("../pics/thumbs/F-7.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_F7.setIcon(icon18)
        self.pushButton_F7.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_F7.setFlat(False)
        self.pushButton_F7.setObjectName("pushButton_F7")
        self.gridLayout_2.addWidget(self.pushButton_F7, 2, 2, 1, 1)
        self.pushButton_F6 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_F6.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_F6.setMaximumSize(QtCore.QSize(140, 140))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("../pics/thumbs/F-6.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_F6.setIcon(icon19)
        self.pushButton_F6.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_F6.setFlat(False)
        self.pushButton_F6.setObjectName("pushButton_F6")
        self.gridLayout_2.addWidget(self.pushButton_F6, 2, 1, 1, 1)
        self.pushButton_4_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4_3.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_4_3.setMaximumSize(QtCore.QSize(140, 140))
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("../pics/thumbs/4-3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4_3.setIcon(icon20)
        self.pushButton_4_3.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_4_3.setFlat(False)
        self.pushButton_4_3.setObjectName("pushButton_4_3")
        self.gridLayout_2.addWidget(self.pushButton_4_3, 2, 0, 1, 1)
        self.pushButton_4_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4_2.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_4_2.setMaximumSize(QtCore.QSize(140, 140))
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("../pics/thumbs/4-2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4_2.setIcon(icon21)
        self.pushButton_4_2.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_4_2.setFlat(False)
        self.pushButton_4_2.setObjectName("pushButton_4_2")
        self.gridLayout_2.addWidget(self.pushButton_4_2, 1, 4, 1, 1)
        self.pushButton_4_1 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4_1.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_4_1.setMaximumSize(QtCore.QSize(140, 140))
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("../pics/thumbs/4-1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4_1.setIcon(icon22)
        self.pushButton_4_1.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_4_1.setFlat(False)
        self.pushButton_4_1.setObjectName("pushButton_4_1")
        self.gridLayout_2.addWidget(self.pushButton_4_1, 1, 3, 1, 1)
        self.pushButton_R3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_R3.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_R3.setMaximumSize(QtCore.QSize(140, 140))
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("../pics/thumbs/R-3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_R3.setIcon(icon23)
        self.pushButton_R3.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_R3.setFlat(False)
        self.pushButton_R3.setObjectName("pushButton_R3")
        self.gridLayout_2.addWidget(self.pushButton_R3, 1, 2, 1, 1)
        self.pushButton_R2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_R2.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_R2.setMaximumSize(QtCore.QSize(140, 140))
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("../pics/thumbs/R-2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_R2.setIcon(icon24)
        self.pushButton_R2.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_R2.setFlat(False)
        self.pushButton_R2.setObjectName("pushButton_R2")
        self.gridLayout_2.addWidget(self.pushButton_R2, 1, 1, 1, 1)
        self.pushButton_F11 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_F11.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_F11.setMaximumSize(QtCore.QSize(140, 140))
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("../pics/thumbs/F-11.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_F11.setIcon(icon25)
        self.pushButton_F11.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_F11.setFlat(False)
        self.pushButton_F11.setObjectName("pushButton_F11")
        self.gridLayout_2.addWidget(self.pushButton_F11, 1, 0, 1, 1)
        self.pushButton_F10 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_F10.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_F10.setMaximumSize(QtCore.QSize(140, 140))
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("../pics/thumbs/F-10.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_F10.setIcon(icon26)
        self.pushButton_F10.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_F10.setFlat(False)
        self.pushButton_F10.setObjectName("pushButton_F10")
        self.gridLayout_2.addWidget(self.pushButton_F10, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 726, 288))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_5_1 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5_1.sizePolicy().hasHeightForWidth())
        self.pushButton_5_1.setSizePolicy(sizePolicy)
        self.pushButton_5_1.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_5_1.setMaximumSize(QtCore.QSize(140, 140))
        self.pushButton_5_1.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_5_1.setText("")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap("../pics/thumbs/5-1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5_1.setIcon(icon27)
        self.pushButton_5_1.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_5_1.setFlat(False)
        self.pushButton_5_1.setObjectName("pushButton_5_1")
        self.gridLayout_3.addWidget(self.pushButton_5_1, 0, 0, 1, 1)
        self.pushButton_6_1 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_6_1.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_6_1.setMaximumSize(QtCore.QSize(140, 140))
        self.pushButton_6_1.setText("")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap("../pics/thumbs/6-1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6_1.setIcon(icon28)
        self.pushButton_6_1.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_6_1.setFlat(False)
        self.pushButton_6_1.setObjectName("pushButton_6_1")
        self.gridLayout_3.addWidget(self.pushButton_6_1, 0, 1, 1, 1)
        self.pushButton_6_2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_6_2.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_6_2.setMaximumSize(QtCore.QSize(140, 140))
        self.pushButton_6_2.setText("")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap("../pics/thumbs/6-2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6_2.setIcon(icon29)
        self.pushButton_6_2.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_6_2.setFlat(False)
        self.pushButton_6_2.setObjectName("pushButton_6_2")
        self.gridLayout_3.addWidget(self.pushButton_6_2, 0, 2, 1, 1)
        self.pushButton_9_1 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_9_1.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_9_1.setMaximumSize(QtCore.QSize(140, 140))
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap("../pics/thumbs/9-1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9_1.setIcon(icon30)
        self.pushButton_9_1.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_9_1.setFlat(False)
        self.pushButton_9_1.setObjectName("pushButton_9_1")
        self.gridLayout_3.addWidget(self.pushButton_9_1, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 4, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 601, 142))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_lev = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_lev.sizePolicy().hasHeightForWidth())
        self.pushButton_lev.setSizePolicy(sizePolicy)
        self.pushButton_lev.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_lev.setMaximumSize(QtCore.QSize(140, 140))
        self.pushButton_lev.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_lev.setText("")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap("../pics/thumbs/level.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_lev.setIcon(icon31)
        self.pushButton_lev.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_lev.setFlat(False)
        self.pushButton_lev.setObjectName("pushButton_lev")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_lev)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 180, 601, 142))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.pushButton_frame = QtWidgets.QPushButton(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_frame.sizePolicy().hasHeightForWidth())
        self.pushButton_frame.setSizePolicy(sizePolicy)
        self.pushButton_frame.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_frame.setMaximumSize(QtCore.QSize(140, 140))
        self.pushButton_frame.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_frame.setText("")
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap("../pics/thumbs/framemodul.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_frame.setIcon(icon32)
        self.pushButton_frame.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_frame.setFlat(False)
        self.pushButton_frame.setObjectName("pushButton_frame")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_frame)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 10, 726, 288))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_diag1 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_diag1.sizePolicy().hasHeightForWidth())
        self.pushButton_diag1.setSizePolicy(sizePolicy)
        self.pushButton_diag1.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_diag1.setMaximumSize(QtCore.QSize(140, 140))
        self.pushButton_diag1.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_diag1.setText("")
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap("../pics/thumbs/diagonal/diag_1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_diag1.setIcon(icon33)
        self.pushButton_diag1.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_diag1.setFlat(False)
        self.pushButton_diag1.setObjectName("pushButton_diag1")
        self.gridLayout_4.addWidget(self.pushButton_diag1, 0, 0, 1, 1)
        self.pushButton_diag2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_diag2.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_diag2.setMaximumSize(QtCore.QSize(140, 140))
        self.pushButton_diag2.setText("")
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap("../pics/thumbs/diagonal/diag_2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_diag2.setIcon(icon34)
        self.pushButton_diag2.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_diag2.setFlat(False)
        self.pushButton_diag2.setObjectName("pushButton_diag2")
        self.gridLayout_4.addWidget(self.pushButton_diag2, 0, 1, 1, 1)
        self.pushButton_diag3 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_diag3.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_diag3.setMaximumSize(QtCore.QSize(140, 140))
        self.pushButton_diag3.setText("")
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap("../pics/thumbs/diagonal/diag_3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_diag3.setIcon(icon35)
        self.pushButton_diag3.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_diag3.setFlat(False)
        self.pushButton_diag3.setObjectName("pushButton_diag3")
        self.gridLayout_4.addWidget(self.pushButton_diag3, 0, 2, 1, 1)
        self.pushButton_diag4 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_diag4.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_diag4.setMaximumSize(QtCore.QSize(140, 140))
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap("../pics/thumbs/diagonal/diag_4.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_diag4.setIcon(icon36)
        self.pushButton_diag4.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_diag4.setFlat(False)
        self.pushButton_diag4.setObjectName("pushButton_diag4")
        self.gridLayout_4.addWidget(self.pushButton_diag4, 0, 3, 1, 1)
        self.pushButton_diag5 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_diag5.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_diag5.setMaximumSize(QtCore.QSize(140, 140))
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap("../pics/thumbs/diagonal/diag_5.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_diag5.setIcon(icon37)
        self.pushButton_diag5.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_diag5.setFlat(False)
        self.pushButton_diag5.setObjectName("pushButton_diag5")
        self.gridLayout_4.addWidget(self.pushButton_diag5, 0, 4, 1, 1)
        self.pushButton_diag6 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_diag6.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_diag6.setMaximumSize(QtCore.QSize(140, 140))
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap("../pics/thumbs/diagonal/diag_6.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_diag6.setIcon(icon38)
        self.pushButton_diag6.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_diag6.setFlat(False)
        self.pushButton_diag6.setObjectName("pushButton_diag6")
        self.gridLayout_4.addWidget(self.pushButton_diag6, 1, 0, 1, 1)
        self.pushButton_diag7 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_diag7.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton_diag7.setMaximumSize(QtCore.QSize(140, 140))
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap("../pics/thumbs/diagonal/diag_7.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_diag7.setIcon(icon39)
        self.pushButton_diag7.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_diag7.setFlat(False)
        self.pushButton_diag7.setObjectName("pushButton_diag7")
        self.gridLayout_4.addWidget(self.pushButton_diag7, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Подпятник v0.6.5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "1-2 Отверстия"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "3-4 Отверстия"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "5-9 Отверстий"))
        self.label.setText(_translate("MainWindow", "- Зарисовать высоты уровней"))
        self.label_2.setText(_translate("MainWindow", "- Зарисовать раму "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Доп. Модули"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Сечения раскосов"))
